Repository CiscoAI/KFLab, pull requests merged in 2018-10, with the labels that each got.

#60 tf-mnist changes for 0.3
  scripts/tf_mnist_app.py
  tf-mnist/cleanup.bash
  tf-mnist/install.bash
  tf-mnist/variables.bash
Labels: size/S

#55 Docs updated
  tf-mnist/README.md
  tf-mnist/variables.bash
Labels: size/M

#61 kubebench changes for v0.3
  config/tf_cnn_benchmarks/tf-cnn-dummy.yaml
  kubebench/cleanup.bash
  kubebench/install.bash
  kubebench/run_kb.bash
  kubebench/variables.bash
  scripts/kubebench_app.py
Labels: approved, lgtm, size/M

#68 pick repo name & owner from env
  test/workflows/components/kubebench.jsonnet
  test/workflows/components/kubebench.libsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/tf_mnist.jsonnet
  test/workflows/components/tf_mnist.libsonnet
Labels: approved, lgtm, size/M

#70 updated readme
  README.md
Labels: approved, lgtm, size/XS
