Repository CiscoAI/KFLab, pull requests merged in 2018-07, with the labels that each got.

#22 pr for testing presubmit job
  README.md
  mnist/README.md
  prow_config.yaml
  scripts/nightly_gke.py
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#25 move common routines to util module and rename script
  scripts/mnist_app.py
  scripts/util.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#26 increase the sleep time for train job & delete cluster in cleanup
  scripts/mnist_app.py
Labels: approved, lgtm, size/XS

#28 prow config update and kb app fixes for prow
  prow_config.yaml
  scripts/kubebench_app.py
  test/workflows/components/kubebench.jsonnet
  test/workflows/components/kubebench.libsonnet
  test/workflows/components/params.libsonnet
Labels: approved, lgtm, size/M

#29 move prow cluster to a separate project
  README.md
  kubebench/README.md
  scripts/kubebench_app.py
  scripts/mnist_app.py
  scripts/nightly.py
  scripts/util.py
  test/workflows/app.yaml
  test/workflows/components/kubebench.libsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#30 minor fixes & clean up debug/stale code
  scripts/kubebench_app.py
  scripts/mnist_app.py
Labels: approved, lgtm, size/M

#36 Modified readme and moved image to gcr.io repository. Issue #35
  mnist/README.md
  mnist/variables.bash
Labels: approved, lgtm, size/M

#37 change existing mnist app name to tf-mnist
  kubebench/README.md
  prow_config.yaml
  scripts/tf_mnist_app.py
  test/workflows/components/params.libsonnet
  test/workflows/components/sample.libsonnet
  test/workflows/components/tf_mnist.jsonnet
  test/workflows/components/tf_mnist.libsonnet
  tf-mnist/Dockerfile
  tf-mnist/README.md
  tf-mnist/cleanup.bash
  tf-mnist/data/0.png
  tf-mnist/data/1.png
  tf-mnist/data/2.png
  tf-mnist/data/3.png
  tf-mnist/data/4.png
  tf-mnist/data/5.png
  tf-mnist/data/6.png
  tf-mnist/data/7.png
  tf-mnist/data/8.png
  tf-mnist/data/9.png
  tf-mnist/install.bash
  tf-mnist/mnist_client.py
  tf-mnist/mnist_model.py
  tf-mnist/pictures/generic_schematic.png
  tf-mnist/pictures/gke_schematic.png
  tf-mnist/pkg/nfs-server/nfs-server.libsonnet
  tf-mnist/pkg/nfs-server/parts.yaml
  tf-mnist/pkg/nfs-server/prototypes/nfs-server.jsonnet
  tf-mnist/pkg/nfs-volume/nfs-volume.libsonnet
  tf-mnist/pkg/nfs-volume/parts.yaml
  tf-mnist/pkg/nfs-volume/prototypes/nfs-volume.jsonnet
  tf-mnist/pkg/registry.yaml
  tf-mnist/pkg/tf-mnistjob/parts.yaml
  tf-mnist/pkg/tf-mnistjob/prototypes/tf-mnist-client.jsonnet
  tf-mnist/pkg/tf-mnistjob/prototypes/tf-mnist.jsonnet
  tf-mnist/pkg/tf-mnistjob/util.libsonnet
  tf-mnist/portf.bash
  tf-mnist/serve.bash
  tf-mnist/train.bash
  tf-mnist/variables.bash
  tf-mnist/webapp/Dockerfile
  tf-mnist/webapp/app.py
  tf-mnist/webapp/config.py
  tf-mnist/webapp/requirements.txt
  tf-mnist/webapp/static/css/style.css
  tf-mnist/webapp/static/data/0.png
  tf-mnist/webapp/static/data/1.png
  tf-mnist/webapp/static/data/2.png
  tf-mnist/webapp/static/data/3.png
  tf-mnist/webapp/static/data/4.png
  tf-mnist/webapp/static/data/5.png
  tf-mnist/webapp/static/data/6.png
  tf-mnist/webapp/static/data/7.png
  tf-mnist/webapp/static/data/8.png
  tf-mnist/webapp/static/data/9.png
  tf-mnist/webapp/static/js/axios.min.js
  tf-mnist/webapp/static/js/main.js
  tf-mnist/webapp/static/js/vue.min.js
  tf-mnist/webapp/templates/main.html
Labels: approved, lgtm, size/L

#38 fix pkg path change
  kubebench/install.bash
  kubebench/variables.bash
  tf-mnist/install.bash
Labels: approved, lgtm, size/XS

#40 Fix for Issue #39
  README.md
Labels: approved, lgtm, size/S

#44 Fixes issue #42
  tf-mnist/README.md
Labels: approved, lgtm, size/XS

#45 replaced deprecated tf.contrib.learn with tf.estimator
  tf-mnist/mnist_model.py
Labels: approved, lgtm, size/XS

#47 Local demo branch
  tf-mnist/demo/README.md
  tf-mnist/demo/app.bash
  tf-mnist/demo/cleanup.bash
  tf-mnist/demo/install.bash
  tf-mnist/demo/serve.bash
  tf-mnist/demo/train.ipynb
  tf-mnist/demo/variables.bash
  tf-mnist/pkg/tf-mnistjob/prototypes/tf-mnist-client-local.jsonnet
Labels: approved, lgtm, size/XL
