Repository CiscoAI/KFLab, pull requests merged in 2018-06, with the labels that each got.

#8 Test prow
  README.md
Labels: do-not-merge/hold, size/XS

#11 Update Readme for web app installation
  mnist/README.md
Labels: lgtm, size/M

#12 Delete unnecessary files
  mnist/README_GKE.md
  mnist/cleanup.bash
  mnist/install_gke.bash
  mnist/portf.bash
Labels: lgtm, size/L

#13 Added images to the readme for mnist
  README.md
  mnist/README.md
  mnist/pictures/don_schematic.png
  mnist/pictures/generic_schematic.png
  mnist/pictures/gke_schematic.png
Labels: size/M

#14 argo workflow for mnist app
  mnist/portf.bash
  scripts/nightly_gke.py
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#19 use release 0.2.0 kubeflow
  mnist/variables.bash
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS
