Repository CiscoAI/KFLab, pull requests merged in 2019-05, with the labels that each got.

#109 Closes #102: Corrects webapp client pod readiness detection
  tf-mnist/webapp.bash
Labels: approved, lgtm, size/M

#108 Closes: #105, Adds command to log from training pod
  tf-mnist/README.md
Labels: approved, lgtm, size/S

#110 Some changes to README based on discussion with L&D team
  tf-mnist/README.md
Labels: approved, lgtm, size/M

#113 Resolved Nodeport issue in webapp.bash Issue No: #111
  tf-mnist/README.md
  tf-mnist/webapp.bash
Labels: approved, lgtm, size/M

#114 Added list of Kubeflow pods Screenshot
  tf-mnist/README.md
  tf-mnist/pictures/installbash-get-pods.png
  tf-mnist/pictures/servebash-get-pods.png
  tf-mnist/pictures/tf-mnistjob-worker-0-logs.png
  tf-mnist/pictures/trainbash-get-pods.png
Labels: size/S

#115 upgrade worker image
  test/workflows/components/kubebench.libsonnet
  test/workflows/components/tf_mnist.libsonnet
Labels: approved, lgtm, size/XS

#117 Update requirements.txt
  tf-mnist/webapp/requirements.txt
Labels: approved, lgtm, size/XS
