Repository CiscoAI/KFLab, pull requests merged in 2019-04, with the labels that each got.

#91 generalize Kubeflow pkg
  pkg/nfs-server/nfs-server.libsonnet
  pkg/nfs-server/parts.yaml
  pkg/nfs-server/prototypes/nfs-server.jsonnet
  pkg/nfs-volume/nfs-volume.libsonnet
  pkg/nfs-volume/parts.yaml
  pkg/nfs-volume/prototypes/nfs-volume.jsonnet
  pkg/registry.yaml
  pkg/tf-appjob/parts.yaml
  pkg/tf-appjob/prototypes/tf-app-client-local.jsonnet
  pkg/tf-appjob/prototypes/tf-app-client.jsonnet
  pkg/tf-appjob/prototypes/tf-app.jsonnet
  pkg/tf-appjob/tf-job.libsonnet
  pkg/tf-appjob/util.libsonnet
Labels: size/XL

#92 Feature/update tf mnist image
  pipelines/tf-mnist/components/deploy-service/Dockerfile
  pipelines/tf-mnist/components/deploy-service/src/deploy.sh
  pipelines/tf-mnist/components/serve/Dockerfile
  pipelines/tf-mnist/components/serve/src/deploy.sh
  pipelines/tf-mnist/mnist_pipeline.png
  pipelines/tf-mnist/tf_mnist_pipeline/tf_mnist_pipeline.py
Labels: bug, priority/p1, size/XL

#93 Updates README with GKE cluster setup info
  tf-mnist/README.md
Labels: size/M

#94 Updates GCP console link
  tf-mnist/README.md
Labels: approved, lgtm, size/XS

#95 Update README order
  tf-mnist/README.md
Labels: approved, lgtm, size/M

#96 Installation instructions for kubectl and ksonnet
  tf-mnist/README.md
Labels: approved, lgtm, size/XS

#97 Make sure to use n1-standard-2
  tf-mnist/README.md
Labels: approved, lgtm, size/XS

#98 update webapp with port-fwd & exclude docker build
  tf-mnist/variables.bash
  tf-mnist/webapp.bash
Labels: approved, lgtm, size/M

#99 Update Readme
  tf-mnist/README.md
Labels: approved, lgtm, size/M

#100 Update README.md
  tf-mnist/README.md
Labels: approved, lgtm, size/XS

#101 Wait loop added for webapp client service creation
  tf-mnist/webapp.bash
Labels: approved, lgtm, size/S

#103 Multiple changes to readme. added comments to DockerFile
  tf-mnist/Dockerfile
  tf-mnist/README.md
  tf-mnist/pictures/gke_cluster_connect.png
  tf-mnist/pictures/gke_cluster_create.png
  tf-mnist/pictures/gke_machine_type.png
  tf-mnist/pictures/gke_shell_connect.png
  tf-mnist/pictures/webapp.png
Labels: approved, lgtm, size/L

#106 Clarifying that cluster has to be manually cleaned up
  tf-mnist/README.md
Labels: approved, lgtm, size/XS

#107 Minor change in text.
  tf-mnist/README.md
Labels: approved, lgtm, size/S
