Repository CiscoAI/KFLab, pull requests merged in 2019-03, with the labels that each got.

#83 Verfied working version of TF-MNIST pipeline
  pipelines/tf-mnist/README.md
  pipelines/tf-mnist/mnist_pipeline.png
  pipelines/tf-mnist/pipeline-config/pv-minio.yaml
  pipelines/tf-mnist/pipeline-config/pv-mysql.yaml
  pipelines/tf-mnist/pipeline-config/storage-class.yaml
  pipelines/tf-mnist/setup_pipelines.sh
  pipelines/tf-mnist/setup_volumemounts.sh
  pipelines/tf-mnist/tf_mnist_pipeline/tf_mnist_pipeline.py
Labels: do-not-merge/hold, lgtm, size/L

#85 Updated KFLab Readme with notes on proxy server.
  tf-mnist/README.md
Labels: size/S

#86 kflab mnist example for miniKF
  tf-mnist/README.md
  tf-mnist/minikf/README.md
  tf-mnist/minikf/cleanup.bash
  tf-mnist/minikf/install.bash
  tf-mnist/minikf/portf.bash
  tf-mnist/minikf/serve.bash
  tf-mnist/minikf/train.bash
  tf-mnist/minikf/variables.bash
  tf-mnist/minikf/webapp.bash
Labels: approved, lgtm, size/L
